"""
Renderer — converts a DraftOutput into a Word DOCX with a Traceability Annex.
Produces two files in OUTPUT_DIR:
  <doc_id>.docx           — the governance document
  <doc_id>_traceability.docx — the traceability annex table
"""
import io
import os
from datetime import datetime, timezone
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from .models import (
    DraftOutput, ControlBundle, PolicyDraftOutput, GOLDEN_TOC,
    StandardDraftOutput, STANDARD_TOC,
    ProcedureDraftOutput, PROCEDURE_TOC,
)
from .config import OUTPUT_DIR


def _set_cell_bg(cell, hex_color: str):
    """Set table cell background color."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), hex_color)
    shd.set(qn("w:val"), "clear")
    tcPr.append(shd)


def _add_heading(doc: Document, text: str, level: int):
    p = doc.add_heading(text, level=level)
    return p


def _build_main_doc(draft: DraftOutput) -> Document:
    doc = Document()

    # Title page
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(f"{draft.doc_type.upper()}: {draft.topic}")
    run.bold = True
    run.font.size = Pt(22)

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(
        f"Organization: {draft.org_name}\n"
        f"Version: {draft.version}\n"
        f"Document ID: {draft.doc_id}\n"
        f"Generated: {draft.generated_at[:10]}"
    ).font.size = Pt(11)

    doc.add_page_break()

    # Table of contents placeholder
    _add_heading(doc, "Table of Contents", 1)
    doc.add_paragraph("[Auto-generated table of contents — update field in Word to populate]")
    doc.add_page_break()

    # Sections
    for s in draft.sections:
        _add_heading(doc, f"{s.section_id}  {s.title}", 1)
        purpose_para = doc.add_paragraph()
        purpose_para.add_run("Purpose: ").bold = True
        purpose_para.add_run(s.purpose)

        for r in s.requirements:
            req_para = doc.add_paragraph(style="List Bullet")
            id_run = req_para.add_run(f"[{r.req_id}]  ")
            id_run.bold = True
            id_run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)
            req_para.add_run(r.text)

            # Citation footnote
            if r.citations:
                cite_para = doc.add_paragraph(style="List Bullet 2")
                cite_para.add_run("Controls cited: ").italic = True
                cite_para.add_run(", ".join(r.mapped_control_ids or r.citations)).font.size = Pt(9)

    doc.add_page_break()

    # Footer note
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_para.add_run(
        f"Generated by AutoAlign Policy Factory | {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    ).font.size = Pt(8)

    return doc


def _build_traceability_annex(
    draft: DraftOutput,
    bundles: list[ControlBundle],
) -> Document:
    doc = Document()

    _add_heading(doc, "Traceability Annex", 1)
    sub = doc.add_paragraph()
    sub.add_run(
        f"Document: {draft.doc_id}  |  {draft.doc_type}: {draft.topic}  |  "
        f"Org: {draft.org_name}  |  Version: {draft.version}"
    ).font.size = Pt(10)

    doc.add_paragraph(
        "This annex maps every requirement to the cybersecurity controls that ground it. "
        "Every normative requirement (SHALL/MUST/REQUIRED/WILL) must have at least one cited control."
    )

    # Build lookup: chunk_id -> bundle
    bundle_map = {b.chunk_id: b for b in bundles}

    # Table: Req ID | Normative | Requirement Text | Cited Chunk IDs | Control IDs | UAE IA ID
    headers = ["Req ID", "Norm?", "Requirement Text", "Cited Chunk IDs", "NIST Control IDs", "UAE IA ID"]
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"

    hdr_row = table.rows[0]
    for i, h in enumerate(headers):
        cell = hdr_row.cells[i]
        cell.text = h
        _set_cell_bg(cell, "1F497D")
        for para in cell.paragraphs:
            for run in para.runs:
                run.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.size = Pt(9)

    for s in draft.sections:
        # Section separator row
        sep_row = table.add_row()
        sep_cell = sep_row.cells[0]
        sep_cell.merge(sep_row.cells[-1])
        sep_cell.text = f"Section {s.section_id}: {s.title}"
        _set_cell_bg(sep_cell, "D9E1F2")
        for para in sep_cell.paragraphs:
            for run in para.runs:
                run.bold = True
                run.font.size = Pt(9)

        for r in s.requirements:
            row = table.add_row()
            cells = row.cells

            cells[0].text = r.req_id
            cells[1].text = "YES" if r.is_normative else "no"

            # Truncate long requirement text for readability
            cells[2].text = r.text[:300] + ("..." if len(r.text) > 300 else "")

            cells[3].text = "\n".join(r.citations) if r.citations else "-"

            # Resolve control IDs from bundles where possible
            resolved_ids: list[str] = []
            uae_ids: list[str] = []
            for cid in r.citations:
                b = bundle_map.get(cid)
                if b:
                    resolved_ids.append(b.control_id)
                    if b.uae_ia_id:
                        uae_ids.append(b.uae_ia_id)
            cells[4].text = "\n".join(resolved_ids) if resolved_ids else ", ".join(r.mapped_control_ids) or "-"
            cells[5].text = "\n".join(sorted(set(uae_ids))) if uae_ids else "-"

            # Colour-code normative rows
            if r.is_normative:
                _set_cell_bg(cells[1], "E2EFDA")

            for cell in cells:
                for para in cell.paragraphs:
                    for run in para.runs:
                        run.font.size = Pt(8)

    return doc


def render(
    draft: DraftOutput,
    bundles: list[ControlBundle],
    output_dir: str = OUTPUT_DIR,
) -> tuple[str, str]:
    """
    Write main DOCX and traceability annex to output_dir.
    Returns (main_path, annex_path).
    """
    os.makedirs(output_dir, exist_ok=True)

    safe_id = draft.doc_id.replace("/", "-").replace("\\", "-")
    main_path   = os.path.join(output_dir, f"{safe_id}.docx")
    annex_path  = os.path.join(output_dir, f"{safe_id}_traceability.docx")

    print(f"[Renderer] Writing main document -> {main_path}")
    main_doc = _build_main_doc(draft)
    main_doc.save(main_path)

    print(f"[Renderer] Writing traceability annex -> {annex_path}")
    annex_doc = _build_traceability_annex(draft, bundles)
    annex_doc.save(annex_path)

    print(f"[Renderer] Done. {sum(1 for r in draft.all_requirements)} requirements rendered, "
          f"{sum(1 for r in draft.all_requirements if r.is_normative)} normative.")
    return main_path, annex_path


# ── Golden Policy renderer ────────────────────────────────────────────────────

_NAVY  = "1F497D"
_STEEL = "4472C4"
_LIGHT = "D9E1F2"
_GREEN = "E2EFDA"
_WHITE = "FFFFFF"

_ROLE_LABELS = {
    "authority_owner_delegates": "Authority / Owner / Delegates",
    "legal":                     "Legal",
    "internal_audit":            "Internal Audit",
    "HR":                        "Human Resources",
    "cybersecurity":             "Cybersecurity Function",
    "other_departments":         "Other Departments",
    "all_staff":                 "All Staff",
}


def _hdr(doc: Document, text: str, level: int = 1):
    p = doc.add_heading(text, level=level)
    for run in p.runs:
        run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)
    return p


def _tbl_hdr_row(table, headers: list[str], bg: str = _NAVY):
    row = table.rows[0]
    for i, h in enumerate(headers):
        c = row.cells[i]
        c.text = h
        _set_cell_bg(c, bg)
        for para in c.paragraphs:
            for run in para.runs:
                run.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.size = Pt(9)


def _small(cell):
    for para in cell.paragraphs:
        for run in para.runs:
            run.font.size = Pt(8)


def render_policy(
    draft: PolicyDraftOutput,
    bundles: list[ControlBundle],
    output_dir: str = OUTPUT_DIR,
) -> tuple[str, str]:
    """
    Render a Golden Policy Baseline document as two DOCX files:
      <doc_id>.docx               — formatted policy document
      <doc_id>_traceability.docx  — control traceability annex with cross-encoder scores
    Returns (main_path, annex_path).
    """
    os.makedirs(output_dir, exist_ok=True)
    safe_id    = draft.doc_id.replace("/", "-")
    main_path  = os.path.join(output_dir, f"{safe_id}.docx")
    annex_path = os.path.join(output_dir, f"{safe_id}_traceability.docx")

    bundle_map = {b.chunk_id: b for b in bundles}
    ctrl_map   = {b.control_id: b for b in bundles}

    # ── Main Policy Document ──────────────────────────────────────────────────
    doc = Document()

    # Cover block
    cover = doc.add_paragraph()
    cover.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = cover.add_run(draft.title_en.upper())
    r.bold = True; r.font.size = Pt(20)
    r.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

    meta_lines = [
        f"Document ID: {draft.doc_id}",
        f"Version: {draft.version}",
        f"Effective Date: {draft.effective_date}",
        f"Owner: {draft.owner}",
        f"Classification: {draft.classification}",
        f"Generated: {draft.generated_at[:10]}",
    ]
    for line in meta_lines:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.add_run(line).font.size = Pt(11)

    doc.add_page_break()

    # Table of Contents (static — exact 6 headings)
    _hdr(doc, "Table of Contents")
    for i, heading in enumerate(GOLDEN_TOC, start=1):
        doc.add_paragraph(f"{i}.  {heading}", style="List Number")
    doc.add_page_break()

    # 1. Objectives
    _hdr(doc, "1.  Objectives")
    doc.add_paragraph(draft.objectives_en)

    # 2. Scope and Applicability
    _hdr(doc, "2.  Scope and Applicability")
    doc.add_paragraph(draft.scope_applicability_en)

    # 3. Policy Elements
    _hdr(doc, "3.  Policy Elements")
    for e in draft.policy_elements:
        p = doc.add_paragraph(style="List Bullet")
        r_id = p.add_run(f"Element {e.element_no}.  ")
        r_id.bold = True
        r_id.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)
        p.add_run(e.statement_en)
        if e.trace:
            refs = ", ".join(t.control_id for t in e.trace)
            note = doc.add_paragraph(style="List Bullet 2")
            note.add_run(f"Controls: {refs}").font.size = Pt(9)

    # 3a. Policy Sub-programs (element 2 expansion)
    _hdr(doc, "3a.  Cybersecurity Policy Suite (Elements 2-1 to 2-34)", level=2)
    tbl = doc.add_table(rows=1, cols=3)
    tbl.style = "Table Grid"
    _tbl_hdr_row(tbl, ["Sub-No", "Name", "Objective"])
    for sp in draft.policy_subprograms:
        row = tbl.add_row()
        row.cells[0].text = sp.sub_no
        row.cells[1].text = sp.name_en
        row.cells[2].text = sp.objective_en
        if sp.references:
            row.cells[2].text += f"\n[Ref: {', '.join(sp.references)}]"
        for cell in row.cells:
            _small(cell)

    # 4. Roles and Responsibilities
    _hdr(doc, "4.  Roles and Responsibilities")
    rr = draft.roles_responsibilities
    for role_key, label in _ROLE_LABELS.items():
        items = getattr(rr, role_key, [])
        _hdr(doc, label, level=2)
        for item in items:
            doc.add_paragraph(item, style="List Bullet")

    # 5. Policy Compliance
    _hdr(doc, "5.  Policy Compliance")
    for i, clause in enumerate(draft.compliance_clauses, start=1):
        p = doc.add_paragraph(style="List Number")
        p.add_run(clause)

    # 6. Exceptions
    _hdr(doc, "6.  Exceptions")
    doc.add_paragraph(draft.exceptions_en)

    # Closing note
    _hdr(doc, "Note", level=2)
    note_p = doc.add_paragraph()
    note_p.add_run(draft.closing_note_en).italic = True

    doc.add_page_break()
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_p.add_run(
        f"Generated by AutoAlign Policy Factory (Golden Policy Baseline) | "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    ).font.size = Pt(8)

    print(f"[Renderer] Writing policy -> {main_path}")
    doc.save(main_path)

    # ── Traceability Annex (cross-encoder sourced controls) ───────────────────
    ann = Document()
    _hdr(ann, "Control Traceability Annex")
    ann.add_paragraph(
        f"Document: {draft.doc_id}  |  {draft.title_en}  |  Version: {draft.version}"
    ).runs[0].font.size = Pt(10)
    ann.add_paragraph(
        "All controls below were sourced via dense retrieval + cross-encoder reranking "
        "(top-20 per query). The 'Rerank Score' column shows the cross-encoder relevance "
        "score for each control relative to its retrieval query. Higher scores indicate "
        "stronger semantic relevance."
    ).runs[0].font.size = Pt(9)

    # Table: Element | Statement (truncated) | Framework | Control ID | Title | NCA ID | Rerank Score
    hdrs = ["Element", "Statement (excerpt)", "Framework", "Control ID", "Control Title", "NCA ID", "Rerank Score"]
    tbl2 = ann.add_table(rows=1, cols=len(hdrs))
    tbl2.style = "Table Grid"
    _tbl_hdr_row(tbl2, hdrs)

    for e in draft.policy_elements:
        for t in e.trace:
            row = tbl2.add_row()
            cells = row.cells
            cells[0].text = f"Element {e.element_no}"
            cells[1].text = e.statement_en[:200] + ("..." if len(e.statement_en) > 200 else "")

            # Resolve from bundle maps
            b_by_id    = ctrl_map.get(t.control_id)
            b_by_chunk = bundle_map.get(t.source_ref)
            b = b_by_id or b_by_chunk

            cells[2].text = t.framework
            cells[3].text = t.control_id
            cells[4].text = b.title if b else "-"
            cells[5].text = (b.nca_id or b.uae_ia_id or "-") if b else "-"
            score = b.rerank_score if b else None
            cells[6].text = f"{score:.4f}" if score is not None else "-"

            if score is not None and score > 5.0:
                _set_cell_bg(cells[6], _GREEN)
            for cell in cells:
                _small(cell)

    # Subprogram catalog table in annex
    _hdr(ann, "Cybersecurity Policy Suite — Full Catalog", level=2)
    tbl3 = ann.add_table(rows=1, cols=4)
    tbl3.style = "Table Grid"
    _tbl_hdr_row(tbl3, ["Sub-No", "Name", "Objective", "References"])
    for sp in draft.policy_subprograms:
        row = tbl3.add_row()
        row.cells[0].text = sp.sub_no
        row.cells[1].text = sp.name_en
        row.cells[2].text = sp.objective_en
        row.cells[3].text = ", ".join(sp.references) if sp.references else "-"
        for cell in row.cells:
            _small(cell)

    print(f"[Renderer] Writing traceability annex -> {annex_path}")
    ann.save(annex_path)

    print(f"[Renderer] Policy render done: {len(draft.policy_elements)} elements, "
          f"{len(draft.policy_subprograms)} subprograms.")
    return main_path, annex_path


# ── Golden Standard renderer ──────────────────────────────────────────────────

def render_standard(
    draft: StandardDraftOutput,
    bundles: list[ControlBundle],
    output_dir: str = OUTPUT_DIR,
) -> tuple[str, str]:
    """
    Render a Golden Standard Baseline document as two DOCX files:
      <doc_id>.docx               — formatted standard document
      <doc_id>_traceability.docx  — control traceability annex with cross-encoder scores
    Returns (main_path, annex_path).
    """
    os.makedirs(output_dir, exist_ok=True)
    safe_id    = draft.doc_id.replace("/", "-")
    main_path  = os.path.join(output_dir, f"{safe_id}.docx")
    annex_path = os.path.join(output_dir, f"{safe_id}_traceability.docx")

    ctrl_map  = {b.control_id: b for b in bundles}
    chunk_map = {b.chunk_id:   b for b in bundles}

    # ── Main Standard Document ────────────────────────────────────────────────
    doc = Document()

    # Cover block
    cover = doc.add_paragraph()
    cover.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = cover.add_run(draft.title_en.upper())
    r.bold = True; r.font.size = Pt(20)
    r.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

    for line in [
        f"Document ID: {draft.doc_id}",
        f"Version: {draft.version}",
        f"Effective Date: {draft.effective_date}",
        f"Owner: {draft.owner}",
        f"Classification: {draft.classification}",
        f"Generated: {draft.generated_at[:10]}",
    ]:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.add_run(line).font.size = Pt(11)

    doc.add_page_break()

    # Table of Contents (static — exact 6 headings)
    _hdr(doc, "Table of Contents")
    for i, heading in enumerate(STANDARD_TOC, start=1):
        doc.add_paragraph(f"{i}.  {heading}", style="List Number")
    doc.add_page_break()

    # Definitions and Terms
    _hdr(doc, "Definitions and Terms")
    tbl_def = doc.add_table(rows=1, cols=2)
    tbl_def.style = "Table Grid"
    _tbl_hdr_row(tbl_def, ["Term", "Definition"])
    for defn in draft.definitions:
        row = tbl_def.add_row()
        row.cells[0].text = defn.term_en
        row.cells[1].text = defn.description_en
        for cell in row.cells:
            _small(cell)

    doc.add_page_break()

    # 1. Objectives
    _hdr(doc, "1.  Objectives")
    doc.add_paragraph(draft.objectives_en)

    # 2. Scope and Applicability
    _hdr(doc, "2.  Scope and Applicability")
    doc.add_paragraph(draft.scope_en)

    # 3. Standards Requirements
    _hdr(doc, "3.  Standards Requirements")
    for dom in draft.domains:
        _hdr(doc, f"Domain {dom.domain_number}: {dom.title_en}", level=2)

        p_obj = doc.add_paragraph()
        p_obj.add_run("Objective: ").bold = True
        p_obj.add_run(dom.objective_en)

        p_risk = doc.add_paragraph()
        p_risk.add_run("Potential Risks: ").bold = True
        p_risk.add_run(dom.potential_risks_en)

        _hdr(doc, "Requirements:", level=3)
        for req in dom.requirements:
            p_req = doc.add_paragraph(style="List Bullet")
            r_id = p_req.add_run(f"{req.req_id}  ")
            r_id.bold = True
            r_id.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)
            p_req.add_run(req.statement_en)
            if req.trace:
                refs = ", ".join(t.control_id for t in req.trace)
                note = doc.add_paragraph(style="List Bullet 2")
                note.add_run(f"Controls: {refs}").font.size = Pt(9)
            if req.placeholders:
                ph_note = doc.add_paragraph(style="List Bullet 2")
                ph_note.add_run(f"Placeholders: {', '.join(req.placeholders)}").font.size = Pt(9)

    # 4. Roles and Responsibilities
    _hdr(doc, "4.  Roles and Responsibilities")
    for role in draft.roles_responsibilities:
        p = doc.add_paragraph(style="List Number")
        p.add_run(f"{role.item_no} ").bold = True
        p.add_run(role.text_en)

    # 5. Update and Review
    _hdr(doc, "5.  Update and Review")
    doc.add_paragraph(draft.review_update_en)

    # 6. Compliance with the Standard
    _hdr(doc, "6.  Compliance with the Standard")
    for i, clause in enumerate(draft.compliance_en, start=1):
        p = doc.add_paragraph(style="List Number")
        p.add_run(clause)

    # Closing Note
    _hdr(doc, "Note", level=2)
    doc.add_paragraph(draft.closing_note_en).runs[0].italic = True if doc.paragraphs[-1].runs else None

    doc.add_page_break()
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_p.add_run(
        f"Generated by AutoAlign Policy Factory (Golden Standard Baseline) | "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    ).font.size = Pt(8)

    print(f"[Renderer] Writing standard -> {main_path}")
    doc.save(main_path)

    # ── Traceability Annex ────────────────────────────────────────────────────
    ann = Document()
    _hdr(ann, "Control Traceability Annex")
    ann.add_paragraph(
        f"Document: {draft.doc_id}  |  {draft.title_en}  |  Version: {draft.version}"
    ).runs[0].font.size = Pt(10)
    ann.add_paragraph(
        "All controls below were sourced via dense retrieval + cross-encoder reranking. "
        "Every 'shall' requirement must be backed by an NCA control. "
        "The 'Rerank Score' column shows the cross-encoder relevance score."
    ).runs[0].font.size = Pt(9)

    hdrs = ["Req ID", "Domain", "Requirement (excerpt)", "Framework", "Control ID", "Control Title", "NCA ID", "Rerank Score"]
    tbl2 = ann.add_table(rows=1, cols=len(hdrs))
    tbl2.style = "Table Grid"
    _tbl_hdr_row(tbl2, hdrs)

    for dom in draft.domains:
        # Domain separator row
        sep_row = tbl2.add_row()
        sep_cell = sep_row.cells[0]
        sep_cell.merge(sep_row.cells[-1])
        sep_cell.text = f"Domain {dom.domain_number}: {dom.title_en}"
        _set_cell_bg(sep_cell, _LIGHT)
        for para in sep_cell.paragraphs:
            for run in para.runs:
                run.bold = True
                run.font.size = Pt(9)

        for req in dom.requirements:
            for t in req.trace:
                row = tbl2.add_row()
                cells = row.cells
                cells[0].text = req.req_id
                cells[1].text = dom.title_en
                cells[2].text = req.statement_en[:200] + ("..." if len(req.statement_en) > 200 else "")
                cells[3].text = t.framework
                cells[4].text = t.control_id

                b = ctrl_map.get(t.control_id) or chunk_map.get(t.source_ref)
                cells[5].text = b.title if b else "-"
                cells[6].text = (b.nca_id or b.uae_ia_id or "-") if b else "-"
                score = b.rerank_score if b else None
                cells[7].text = f"{score:.4f}" if score is not None else "-"

                if score is not None and score > 5.0:
                    _set_cell_bg(cells[7], _GREEN)
                for cell in cells:
                    _small(cell)

    print(f"[Renderer] Writing standard traceability annex -> {annex_path}")
    ann.save(annex_path)

    total_reqs = sum(len(d.requirements) for d in draft.domains)
    print(f"[Renderer] Standard render done: {len(draft.domains)} domains, {total_reqs} requirements.")
    return main_path, annex_path


# ── Golden Procedure renderer ─────────────────────────────────────────────────

_MONO = "Courier New"


def _add_code_block(doc: Document, code: str, caption: str = ""):
    """Render a code block with gray shaded background."""
    if caption:
        cap_p = doc.add_paragraph()
        cap_p.add_run(caption).bold = True

    for line in code.split("\n"):
        p = doc.add_paragraph()
        # Gray background shading
        pPr = p._p.get_or_add_pPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"), "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"), "F2F2F2")
        pPr.append(shd)
        # Left indent to visually offset from body text
        ind = OxmlElement("w:ind")
        ind.set(qn("w:left"), "360")
        pPr.append(ind)

        r = p.add_run(line if line else " ")
        r.font.name  = _MONO
        r.font.size  = Pt(9)
        r.font.color.rgb = RGBColor(0x18, 0x20, 0x28)


def _add_diagram_explanation(doc: Document, text: str):
    """Add an italic, grey explanatory paragraph below a diagram."""
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.italic = True
    r.font.size = Pt(9)
    r.font.color.rgb = RGBColor(0x55, 0x55, 0x55)


# ── PlantUML Encoding + Rendering ────────────────────────────────────────────

_PLANTUML_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_"


def _plantuml_encode(text: str) -> str:
    """Encode PlantUML source for use in plantuml.com/plantuml/png/{encoded} URLs.
    PlantUML uses raw deflate (no zlib header/trailer) + its own base64 alphabet."""
    import zlib
    compressed = zlib.compress(text.encode("utf-8"), level=9)[2:-4]
    result = []
    for i in range(0, len(compressed), 3):
        b0 = compressed[i] if i < len(compressed) else 0
        b1 = compressed[i + 1] if i + 1 < len(compressed) else 0
        b2 = compressed[i + 2] if i + 2 < len(compressed) else 0
        result += [
            _PLANTUML_CHARS[(b0 >> 2) & 0x3F],
            _PLANTUML_CHARS[((b0 & 3) << 4) | ((b1 >> 4) & 0xF)],
            _PLANTUML_CHARS[((b1 & 0xF) << 2) | ((b2 >> 6) & 3)],
            _PLANTUML_CHARS[b2 & 0x3F],
        ]
    return "".join(result)


def _plantuml_to_png(puml_code: str) -> bytes | None:
    """Render PlantUML source to PNG via the plantuml.com public server."""
    try:
        import requests as _req
        encoded = _plantuml_encode(puml_code)
        url = f"https://www.plantuml.com/plantuml/png/{encoded}"
        resp = _req.get(url, timeout=45)
        if resp.status_code == 200 and len(resp.content) > 512:
            if resp.content[:4] == b"\x89PNG":
                print(f"[Renderer] PlantUML render succeeded ({len(resp.content)} bytes).")
                return resp.content
        print(f"[Renderer] PlantUML returned {resp.status_code}; falling back.")
    except Exception as exc:
        print(f"[Renderer] PlantUML render failed ({exc}); falling back.")
    return None


def _add_plantuml_block(doc: Document, puml_code: str, figure_label: str):
    """
    Embed a PlantUML diagram as a PNG image in the DOCX.
    Renders via plantuml.com public API; falls back to a text code block if offline.
    """
    fig_p = doc.add_paragraph()
    fig_p.add_run(figure_label).bold = True

    if puml_code and "@startuml" in puml_code:
        png_bytes = _plantuml_to_png(puml_code)
        if png_bytes:
            try:
                doc.add_picture(io.BytesIO(png_bytes), width=Inches(5.5))
                doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
                return
            except Exception as exc:
                print(f"[Renderer] Failed to insert PlantUML PNG ({exc}); falling back to text block.")

    # Fallback: raw PlantUML code block with note
    fig_p.add_run("  (paste into plantuml.com to render)").italic = True
    code = puml_code or "(no diagram source provided)"
    for line in code.strip().split("\n"):
        p = doc.add_paragraph()
        r = p.add_run(line if line else " ")
        r.font.name  = _MONO
        r.font.size  = Pt(9)
        r.font.color.rgb = RGBColor(0x00, 0x5C, 0x99)


def _render_swimlane_from_spec(spec) -> bytes | None:
    """
    Render a SwimlaneSpec as a PNG — professional Visio-style swimlane.

    Key design decisions vs. the old renderer:
    - 6.5" wide (full letter content width) gives ~1.1" per column for 5 cols.
    - Column headers have white borders so they appear as distinct labelled cells.
    - Multiple nodes in the same cell are stacked VERTICALLY (each gets full box width).
    - Same-row edges: straight horizontal arrows using shape-boundary connector points.
    - Cross-row edges: L-shaped elbow connectors (down/up + horizontal turn) — no diagonals.
    - Backward same-row edges: gentle arc looping above the lane.
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.patches as mpatches
        from matplotlib.patches import FancyBboxPatch, Ellipse
        from collections import defaultdict
        import textwrap as _tw
        import io as _io

        rows    = spec.rows
        columns = spec.columns
        nodes   = spec.nodes
        edges   = spec.edges
        n_rows  = len(rows)
        n_cols  = len(columns)

        if not n_rows or not n_cols or not nodes:
            return None

        # ── Lookup maps ───────────────────────────────────────────────────────
        row_idx = {r.id: i for i, r in enumerate(rows)}
        col_idx = {c.id: i for i, c in enumerate(columns)}

        # ── Layout (all in inches) ────────────────────────────────────────────
        INSERTION_W = 6.5          # also the Word insertion width
        LABEL_W     = 1.05         # row-label column width
        COL_W       = (INSERTION_W - LABEL_W) / n_cols

        T_TITLE = 9.5
        T_HDR   = 7.5
        T_LABEL = 7.5
        T_NODE  = 6.5

        BOX_W          = COL_W * 0.82          # node box width (1 node per cell)
        CHARS_PER_LINE = max(10, int(BOX_W / 0.054))  # ~0.054" per char at 6.5pt
        LINE_H         = 0.145                 # height per text line
        BOX_PAD        = 0.18                  # extra vertical padding (prevents text bleeding)

        TITLE_H = 0.40
        HDR_H   = 0.36

        # ── Group nodes by cell early so dynamic ROW_H can be computed ────────
        cell_nodes: dict = defaultdict(list)
        for node in nodes:
            _ri = row_idx.get(node.row_id, 0)
            _ci = col_idx.get(node.col_id, 0)
            cell_nodes[(_ri, _ci)].append(node)

        # Each vertical slot must comfortably fit a 3-line node + gap above/below
        _max_per_cell = max((len(v) for v in cell_nodes.values()), default=1)
        _SLOT_H = 3 * LINE_H + BOX_PAD + 0.25   # ≈ 0.775" per slot
        ROW_H   = max(1.90, (_max_per_cell + 1) * _SLOT_H)

        fig_w = INSERTION_W
        fig_h = TITLE_H + HDR_H + n_rows * ROW_H

        fig, ax = plt.subplots(figsize=(fig_w, fig_h))
        ax.set_xlim(0, fig_w)
        ax.set_ylim(0, fig_h)
        ax.axis("off")
        fig.patch.set_facecolor("white")

        # ── Colours ───────────────────────────────────────────────────────────
        C_BLUE      = "#1F497D"
        C_BLUE_LITE = "#DCE6F1"
        C_WHITE     = "#FFFFFF"
        C_BORDER    = "#000000"
        C_CELL_BG   = "#FFFFFF"
        C_START_END = "#C5D9EE"
        C_DECISION  = "#FFF2CC"
        C_ARROW     = "#2C2C2C"

        # ── Primitive helpers ─────────────────────────────────────────────────
        def _rect(x, y, w, h, fc=C_CELL_BG, ec=C_BORDER, lw=0.8, z=1):
            ax.add_patch(mpatches.Rectangle(
                (x, y), w, h, fc=fc, ec=ec, lw=lw, zorder=z, clip_on=False))

        def _t(x, y, s, sz=T_NODE, bold=False, italic=False,
               color="#000000", ha="center", va="center", z=5):
            ax.text(x, y, s, fontsize=sz,
                    fontweight="bold" if bold else "normal",
                    fontstyle="italic" if italic else "normal",
                    color=color, ha=ha, va=va, zorder=z, clip_on=False)

        def _wrap(label, max_chars):
            # break_long_words=False prevents ugly mid-word splits like "Adminis"+"trator"
            lines = _tw.wrap(label, width=max(6, max_chars), break_long_words=False)
            return lines or [label]

        def _multiline(cx, cy, label, sz, max_chars, color="#000000", bold=False, z=5):
            """Draw wrapped text centred on (cx, cy)."""
            lines = _wrap(label, max_chars)
            n = len(lines)
            top_y = cy + (n - 1) * LINE_H / 2
            for i, line in enumerate(lines):
                _t(cx, top_y - i * LINE_H, line, sz=sz, color=color, bold=bold, z=z)

        def _short(s, n): return s[:n - 1] + "…" if len(s) > n else s

        # ── Title bar ─────────────────────────────────────────────────────────
        ty = fig_h - TITLE_H
        _rect(0, ty, fig_w, TITLE_H, fc=C_BLUE, ec=C_BLUE, lw=0, z=1)
        _t(fig_w / 2, ty + TITLE_H / 2, _short(spec.title, 72),
           sz=T_TITLE, bold=True, color=C_WHITE, z=5)

        # ── Column headers (white borders create visible cell separators) ──────
        hy = ty - HDR_H
        _rect(0, hy, LABEL_W, HDR_H, fc=C_BLUE, ec=C_WHITE, lw=1.2, z=2)
        hdr_chars = max(8, int(COL_W * 0.88 / 0.058))
        for ci, col in enumerate(columns):
            cx_col = LABEL_W + ci * COL_W
            _rect(cx_col, hy, COL_W, HDR_H, fc=C_BLUE, ec=C_WHITE, lw=1.2, z=2)
            _multiline(cx_col + COL_W / 2, hy + HDR_H / 2, col.label,
                       sz=T_HDR, max_chars=hdr_chars, color=C_WHITE, bold=True, z=4)

        # ── Row lanes ─────────────────────────────────────────────────────────
        lbl_chars = max(6, int(LABEL_W * 0.72 / 0.060))  # ~12 chars → word-boundary 2-line wrap
        for ri, row in enumerate(rows):
            ry = hy - (ri + 1) * ROW_H
            _rect(0, ry, LABEL_W, ROW_H, fc=C_BLUE_LITE, ec=C_BORDER, lw=1.2, z=2)
            _multiline(LABEL_W / 2, ry + ROW_H / 2, row.label,
                       sz=T_LABEL, max_chars=lbl_chars, color=C_BLUE, bold=True, z=4)
            for ci in range(n_cols):
                _rect(LABEL_W + ci * COL_W, ry, COL_W, ROW_H,
                      fc=C_CELL_BG, ec=C_BORDER, lw=0.6, z=1)

        # Dashed column separators (subtle guide lines)
        for ci in range(1, n_cols):
            sx = LABEL_W + ci * COL_W
            ax.plot([sx, sx], [0, hy], ls="--", color="#B8B8B8", lw=0.5, zorder=2)

        # ── Draw nodes — vertical stacking within cell ────────────────────────
        node_bbox: dict = {}  # node.id → (cx, cy, half_w, half_h)

        for (ri, ci), cnodes in cell_nodes.items():
            n_in_cell = len(cnodes)
            cell_x  = LABEL_W + ci * COL_W
            cell_y  = hy - (ri + 1) * ROW_H   # bottom of lane (matplotlib y)
            cx_cell = cell_x + COL_W / 2       # horizontal centre of cell

            # Evenly distribute nodes top→bottom within the lane
            slot_h = ROW_H / (n_in_cell + 1)
            # y positions from top of lane downward (in matplotlib: from high y to low y)
            node_ys = [cell_y + ROW_H - slot_h * (k + 1) for k in range(n_in_cell)]

            for k, node in enumerate(cnodes):
                bx    = cx_cell
                by    = node_ys[k]
                lines = _wrap(node.label, CHARS_PER_LINE)
                bh    = max(len(lines) * LINE_H + BOX_PAD, 0.28)
                bw    = BOX_W
                shape = node.shape

                if shape in ("start", "end"):
                    ew, eh = bw * 1.05, bh * 1.10
                    ax.add_patch(Ellipse(
                        (bx, by), ew, eh,
                        fc=C_START_END, ec=C_BORDER, lw=0.9, zorder=4))
                    _multiline(bx, by, node.label,
                               sz=T_NODE, max_chars=CHARS_PER_LINE, z=6)
                    node_bbox[node.id] = (bx, by, ew / 2, eh / 2)

                elif shape == "decision":
                    dw = bw * 0.65
                    dh = max(bh * 1.05, 0.36)   # tall enough for text + padding
                    ax.add_patch(plt.Polygon(
                        [[bx, by + dh], [bx + dw, by],
                         [bx, by - dh], [bx - dw, by]],
                        closed=True, fc=C_DECISION, ec=C_BORDER, lw=0.9, zorder=4))
                    # Wrap to ~70% of diamond half-width so text stays inside the shape
                    d_chars = max(6, int(dw * 1.4 / 0.054))
                    _multiline(bx, by, node.label,
                               sz=T_NODE, max_chars=d_chars, z=6)
                    node_bbox[node.id] = (bx, by, dw, dh)

                else:  # process (rounded rectangle)
                    ax.add_patch(FancyBboxPatch(
                        (bx - bw / 2, by - bh / 2), bw, bh,
                        boxstyle="round,pad=0.01",
                        fc=C_CELL_BG, ec=C_BORDER, lw=0.8, zorder=4))
                    _multiline(bx, by, node.label,
                               sz=T_NODE, max_chars=CHARS_PER_LINE, z=6)
                    node_bbox[node.id] = (bx, by, bw / 2, bh / 2)

        # ── node id → row/col id lookups ─────────────────────────────────────
        _node_row = {n.id: n.row_id for n in nodes}
        _node_col = {n.id: n.col_id for n in nodes}

        # ── Draw edges ────────────────────────────────────────────────────────
        AP = dict(arrowstyle="->", color=C_ARROW, lw=0.8,
                  mutation_scale=8, shrinkA=0, shrinkB=0)

        def _lbl(x, y, text):
            ax.text(x, y, text, fontsize=5.5, ha="center", va="bottom",
                    color="#333333", zorder=9,
                    bbox=dict(fc="white", ec="none", pad=0.5))

        def _arrowhead(xy, xytext):
            ax.annotate("", xy=xy, xytext=xytext,
                        arrowprops={**AP, "connectionstyle": "arc3,rad=0.0"},
                        zorder=7)

        def _seg(*pts, z=3):
            xs = [p[0] for p in pts]
            ys = [p[1] for p in pts]
            ax.plot(xs, ys, color=C_ARROW, lw=0.8,
                    solid_capstyle="round", solid_joinstyle="round", zorder=z)

        for edge in edges:
            if edge.from_id not in node_bbox or edge.to_id not in node_bbox:
                continue
            if edge.from_id == edge.to_id:
                continue

            x1, y1, hw1, hh1 = node_bbox[edge.from_id]
            x2, y2, hw2, hh2 = node_bbox[edge.to_id]
            same_lane = (_node_row.get(edge.from_id) == _node_row.get(edge.to_id))
            same_col  = abs(x2 - x1) <= COL_W * 0.35
            ci_from   = col_idx.get(_node_col.get(edge.from_id), 0)
            ci_to     = col_idx.get(_node_col.get(edge.to_id),   0)
            ri_from   = row_idx.get(_node_row.get(edge.from_id), 0)
            ri_to     = row_idx.get(_node_row.get(edge.to_id),   0)

            if same_lane and not same_col:
                # ── Same row, different columns ───────────────────────────────
                forward = ci_to > ci_from
                if forward:
                    ex, ey   = x1 + hw1, y1          # exit right
                    enx, eny = x2 - hw2, y2          # enter left
                    bnd_x = LABEL_W + (ci_from + 1) * COL_W   # right boundary of source col
                    if abs(ey - eny) < 0.02:
                        # Same y — perfectly horizontal arrow
                        _arrowhead((enx, eny), (ex, ey))
                    else:
                        # Stair-step: horiz to col-boundary → vert → horiz arrowhead
                        # Keeps the path in the inter-column corridor, never crossing nodes
                        _seg((ex, ey), (bnd_x, ey), (bnd_x, eny))
                        _arrowhead((enx, eny), (bnd_x, eny))
                    if edge.label:
                        _lbl(bnd_x + (enx - bnd_x) * 0.5, eny + 0.06, edge.label)
                else:
                    # Backward (loop-back) — gentle arc above the lane
                    ex, ey   = x1 - hw1, y1
                    enx, eny = x2 + hw2, y2
                    ax.annotate("", xy=(enx, eny), xytext=(ex, ey),
                                arrowprops={**AP, "connectionstyle": "arc3,rad=-0.30"},
                                zorder=7)
                    if edge.label:
                        _lbl((ex + enx) * 0.5, max(ey, eny) + 0.12, edge.label)

            else:
                # ── Cross-row (or same-cell vertical) ────────────────────────
                going_down = y2 < y1   # y increases upward in matplotlib
                if going_down:
                    ex, ey   = x1, y1 - hh1   # exit bottom
                    enx, eny = x2, y2 + hh2   # enter top
                else:
                    ex, ey   = x1, y1 + hh1   # exit top
                    enx, eny = x2, y2 - hh2   # enter bottom

                # For ALL cross-row edges (same-col or different-col) route via the
                # column gutter so the vertical segment never passes through node boxes
                # in intermediate rows.
                right_gutter = LABEL_W + (ci_from + 1) * COL_W - 0.04
                left_gutter  = LABEL_W + ci_from * COL_W + 0.04
                if same_col:
                    # Use right gutter normally; left gutter for the rightmost column
                    # (right gutter would fall outside the figure boundary).
                    if ci_from < n_cols - 1:
                        gutter_x = right_gutter
                        gex,  gey  = x1 + hw1, y1
                        genx, geny = x2 + hw2, y2
                    else:
                        gutter_x = left_gutter
                        gex,  gey  = x1 - hw1, y1
                        genx, geny = x2 - hw2, y2
                    _seg((gex, gey), (gutter_x, gey), (gutter_x, geny))
                    _arrowhead((genx, geny), (gutter_x, geny))
                    if edge.label:
                        _lbl(gutter_x + (0.08 if ci_from < n_cols - 1 else -0.08),
                             (gey + geny) * 0.5, edge.label)
                else:
                    # Cross-row + different column — 4-point path via gutter
                    if going_down:
                        channel_y = hy - ri_to * ROW_H - 0.10
                    else:
                        channel_y = hy - (ri_to + 1) * ROW_H + 0.10
                    route_x = (gutter_x if ci_to >= ci_from
                                else LABEL_W + ci_from * COL_W + 0.04)
                    _seg((ex, ey), (route_x, ey), (route_x, channel_y), (enx, channel_y))
                    _arrowhead((enx, eny), (enx, channel_y))
                    if edge.label:
                        _lbl((route_x + enx) * 0.5, channel_y + 0.06, edge.label)

        # ── Save ──────────────────────────────────────────────────────────────
        buf = _io.BytesIO()
        fig.savefig(buf, format="png", dpi=150,
                    bbox_inches="tight", facecolor="white", pad_inches=0.05)
        plt.close(fig)
        buf.seek(0)
        data = buf.read()
        return data if data[:4] == b"\x89PNG" else None

    except Exception as exc:
        print(f"[Renderer] Swimlane from spec failed: {exc}")
        import traceback; traceback.print_exc()
        return None


def _render_swimlane_fallback(draft: ProcedureDraftOutput) -> bytes | None:
    """
    Visio-style swimlane renderer — horizontal role lanes × vertical phase columns.
    Derives layout directly from draft structure (no LLM required).
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.patches as mpatches
        from matplotlib.patches import FancyBboxPatch
        from matplotlib.lines import Line2D
        from collections import defaultdict
        import io as _io
        import textwrap as _tw

        phases = draft.phases
        roles  = [r.role_title for r in draft.roles_responsibilities]
        if not phases or not roles:
            return None

        n_phases = len(phases)
        n_roles  = len(roles)

        # ── Layout constants ─────────────────────────────────────────────────
        LABEL_W  = 1.80   # role-label column (inches)
        PHASE_W  = 2.60   # width per phase column
        TITLE_H  = 0.44
        HDR_H    = 0.38
        NODE_H   = 0.62   # node box height (taller = no text clipping)
        NODE_GAP = 0.22   # gap between stacked nodes in the same cell
        LANE_PAD = 0.24   # padding above/below stack within a lane

        # ── Visio-accurate colour palette ────────────────────────────────────
        C_TITLE  = "#1F3864"   # title bar — Visio dark navy
        C_HDR_BG = "#4472C4"   # phase column headers — Visio standard blue
        C_LANE_A = "#BDD7EE"   # lane label — Visio light-blue accent 1 (light)
        C_LANE_B = "#DEEAF1"   # alternate lane label — Visio accent 1 (lighter)
        C_CELL_A = "#EBF3FB"   # grid cell tint A
        C_CELL_B = "#F7FBFF"   # grid cell tint B
        C_NODE   = "#DEEAF1"   # process-box fill — Visio "Process" default fill
        C_BORDER = "#2E75B6"   # process-box border — Visio medium blue
        C_BADGE  = "#4472C4"   # step-number badge fill
        C_GRID   = "#BDD7EE"   # cell grid lines
        C_ARROW  = "#404040"   # connector colour
        C_WHITE  = "#FFFFFF"
        C_NAVY   = "#1F3864"   # text on lane labels
        C_SEP    = "#9DB8D2"   # dashed phase separator

        # ── Role → index matcher ─────────────────────────────────────────────
        def _match_role(actor: str) -> int:
            al = actor.lower()
            best, best_score = 0, 0
            for i, r in enumerate(roles):
                score = len({w for w in al.split() if len(w) > 3}
                            & {w for w in r.lower().split() if len(w) > 3})
                if score > best_score:
                    best, best_score = i, score
            return best

        # Assign each step to (phase_idx, role_idx)
        cell_steps: dict = defaultdict(list)
        for pi, ph in enumerate(phases):
            for st in ph.steps:
                cell_steps[(pi, _match_role(st.actor))].append(st)

        # Per-role lane height = enough to fit the tallest cell stack
        max_per_role: dict[int, int] = {}
        for (pi, ai), sts in cell_steps.items():
            max_per_role[ai] = max(max_per_role.get(ai, 0), len(sts))

        def _lane_h(ai: int) -> float:
            n = max_per_role.get(ai, 0)
            return max(NODE_H + 2 * LANE_PAD,
                       n * NODE_H + (n - 1) * NODE_GAP + 2 * LANE_PAD)

        lane_h = [_lane_h(ai) for ai in range(n_roles)]
        total_lane_h = sum(lane_h)

        fig_w = LABEL_W + n_phases * PHASE_W
        fig_h = TITLE_H + HDR_H + total_lane_h

        fig, ax = plt.subplots(figsize=(fig_w, fig_h), dpi=150)
        ax.set_xlim(0, fig_w)
        ax.set_ylim(0, fig_h)
        ax.axis("off")
        fig.patch.set_facecolor("white")
        fig.subplots_adjust(left=0, right=1, top=1, bottom=0)

        # ── Drawing helpers ──────────────────────────────────────────────────
        def _rect(x, y, w, h, fc=C_NODE, ec=C_BORDER, lw=1.0, z=1, alpha=1.0):
            ax.add_patch(mpatches.Rectangle(
                (x, y), w, h, fc=fc, ec=ec, lw=lw, zorder=z, alpha=alpha, clip_on=False))

        def _txt(x, y, s, sz=7, bold=False, color="#000",
                 ha="center", va="center", z=4, wrap=False):
            ax.text(x, y, s, ha=ha, va=va, fontsize=sz, color=color, zorder=z,
                    fontweight="bold" if bold else "normal",
                    wrap=wrap, clip_on=False)

        def _wrap_str(s: str, w: int) -> list[str]:
            lines = _tw.wrap(s, width=max(8, w), break_long_words=False)
            return lines[:3] or [s[:w]]

        def _multiline(cx, cy, lines, sz, lh, color="#000", bold=False, z=5):
            n   = len(lines)
            top = cy + (n - 1) * lh / 2
            for i, line in enumerate(lines):
                _txt(cx, top - i * lh, line, sz=sz, color=color, bold=bold, z=z)

        def _trunc(s, n):
            return s[:n - 1] + "…" if len(s) > n else s

        # ── Lane y-offsets (bottom of each lane, drawn bottom-up) ────────────
        lane_y: list[float] = []
        y_cur = 0.0
        for ai in range(n_roles - 1, -1, -1):
            lane_y.insert(0, y_cur)
            y_cur += lane_h[ai]

        # ── Title bar ────────────────────────────────────────────────────────
        ty = fig_h - TITLE_H
        _rect(0, ty, fig_w, TITLE_H, fc=C_TITLE, ec=C_TITLE, lw=0, z=2)
        _txt(fig_w / 2, ty + TITLE_H / 2, _trunc(draft.title_en, 90),
             sz=10, bold=True, color=C_WHITE, z=5)

        # ── Phase column headers ─────────────────────────────────────────────
        hy = ty - HDR_H
        _rect(0, hy, LABEL_W, HDR_H, fc=C_HDR_BG, ec=C_HDR_BG, lw=0, z=2)
        ph_chars = max(10, int(PHASE_W * 0.82 / 0.060))
        for pi, ph in enumerate(phases):
            px = LABEL_W + pi * PHASE_W
            _rect(px, hy, PHASE_W, HDR_H, fc=C_HDR_BG, ec=C_WHITE, lw=0.8, z=2)
            ph_lines = _wrap_str(ph.phase_name, ph_chars)
            _multiline(px + PHASE_W / 2, hy + HDR_H / 2, ph_lines,
                       sz=8, lh=0.14, color=C_WHITE, bold=True, z=5)

        # ── Lane rows ────────────────────────────────────────────────────────
        role_chars = max(8, int(LABEL_W * 0.80 / 0.068))
        for ai, role in enumerate(roles):
            ry = lane_y[ai]
            lh = lane_h[ai]
            lane_fc = C_LANE_A if ai % 2 == 0 else C_LANE_B
            _rect(0, ry, LABEL_W, lh, fc=lane_fc, ec=C_BORDER, lw=1.4, z=2)
            rl = _wrap_str(role, role_chars)
            _multiline(LABEL_W / 2, ry + lh / 2, rl,
                       sz=7.5, lh=0.155, color=C_NAVY, bold=True, z=5)
            # Grid cells — alternating tint
            for pi in range(n_phases):
                cell_fc = C_CELL_A if ai % 2 == 0 else C_CELL_B
                _rect(LABEL_W + pi * PHASE_W, ry, PHASE_W, lh,
                      fc=cell_fc, ec=C_GRID, lw=0.5, z=1)

        # Phase separator dashed lines
        for pi in range(1, n_phases):
            sx = LABEL_W + pi * PHASE_W
            ax.plot([sx, sx], [0, hy], ls="--", color=C_SEP, lw=0.8, zorder=3)

        # ── Step nodes ───────────────────────────────────────────────────────
        NODE_W    = PHASE_W * 0.80
        lbl_chars = max(12, int(NODE_W / 0.050))   # ~chars per line at 6pt
        LINE_H    = 0.130
        # step_no → (centre_x, centre_y)
        spos: dict[str, tuple[float, float]] = {}

        for (pi, ai), sts in sorted(cell_steps.items()):
            n      = len(sts)
            cell_x = LABEL_W + pi * PHASE_W + PHASE_W / 2
            ry     = lane_y[ai]
            lh     = lane_h[ai]
            stack_h = n * NODE_H + (n - 1) * NODE_GAP
            top_y   = ry + lh / 2 + stack_h / 2 - NODE_H / 2

            for si, st in enumerate(sts):
                cy = top_y - si * (NODE_H + NODE_GAP)   # node centre y
                cx = cell_x

                # Visio-style process box — light blue fill, medium-blue border
                ax.add_patch(FancyBboxPatch(
                    (cx - NODE_W / 2, cy - NODE_H / 2), NODE_W, NODE_H,
                    boxstyle="round,pad=0.018",
                    fc=C_NODE, ec=C_BORDER, lw=1.5, zorder=4, clip_on=False))

                # Step-number badge — small circle at top-left corner of box
                BADGE_R = 0.115
                bx_badge = cx - NODE_W / 2 + BADGE_R + 0.06
                by_badge = cy + NODE_H / 2 - BADGE_R - 0.06
                ax.add_patch(plt.Circle(
                    (bx_badge, by_badge), BADGE_R,
                    fc=C_BADGE, ec=C_WHITE, lw=0.8, zorder=6, clip_on=False))
                _txt(bx_badge, by_badge,
                     st.step_no, sz=5.5, bold=True, color=C_WHITE, z=7)

                # Action label — centred in box, clear of the badge
                label = st.action.split(".")[0].strip()
                lines = _wrap_str(label, lbl_chars)
                # Shift text centre slightly down so it clears the badge area
                text_cy = cy - BADGE_R * 0.5
                _multiline(cx, text_cy, lines, sz=6, lh=LINE_H, color="#1A1A2E", z=6)

                spos[st.step_no] = (cx, cy)

        # ── Arrows ───────────────────────────────────────────────────────────
        AP = dict(arrowstyle="-|>", color=C_ARROW, lw=1.0, mutation_scale=10)

        def _arrow(x1, y1, x2, y2, style="arc3,rad=0.0"):
            ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                        arrowprops={**AP, "connectionstyle": style},
                        zorder=7, clip_on=False)

        # Within-phase vertical arrows (step N → step N+1 in same phase)
        for ph in phases:
            prev = None
            for st in ph.steps:
                pos = spos.get(st.step_no)
                if pos and prev and prev != pos:
                    px1, py1 = prev
                    px2, py2 = pos
                    # Exit bottom of upper node, enter top of lower node
                    _arrow(px1, py1 - NODE_H / 2, px2, py2 + NODE_H / 2)
                if pos:
                    prev = pos

        # Cross-phase connector: last step of phase N → first step of phase N+1
        # Route: right-edge of last node → elbow at phase-boundary mid-channel
        #        → left-edge of first node in next phase (L-shaped, no diagonals)
        phase_last: list[str | None]  = []
        phase_first: list[str | None] = []
        for ph in phases:
            phase_first.append(ph.steps[0].step_no  if ph.steps else None)
            phase_last.append( ph.steps[-1].step_no if ph.steps else None)

        for pi in range(n_phases - 1):
            last_id  = phase_last[pi]
            first_id = phase_first[pi + 1]
            if last_id and first_id and last_id in spos and first_id in spos:
                x1, y1 = spos[last_id]
                x2, y2 = spos[first_id]
                # Elbow channel runs just inside the right boundary of phase pi
                channel_x = LABEL_W + (pi + 1) * PHASE_W - 0.06
                # Segment 1: right edge of last node → channel_x (horizontal)
                ax.plot([x1 + NODE_W / 2, channel_x], [y1, y1],
                        color=C_ARROW, lw=1.2, solid_capstyle="round", zorder=7)
                # Segment 2: channel_x, y1 → channel_x, y2 (vertical)
                ax.plot([channel_x, channel_x], [y1, y2],
                        color=C_ARROW, lw=1.2, solid_capstyle="round", zorder=7)
                # Segment 3: channel_x → left edge of first node (horizontal, arrowhead)
                ax.annotate("", xy=(x2 - NODE_W / 2, y2),
                            xytext=(channel_x, y2),
                            arrowprops={**AP, "connectionstyle": "arc3,rad=0.0"},
                            zorder=7, clip_on=False)

        buf = _io.BytesIO()
        fig.savefig(buf, format="png", dpi=150,
                    bbox_inches="tight", facecolor="white", pad_inches=0.08)
        plt.close(fig)
        buf.seek(0)
        data = buf.read()
        return data if data[:4] == b"\x89PNG" else None
    except Exception as exc:
        print(f"[Renderer] Swimlane fallback failed: {exc}")
        import traceback; traceback.print_exc()
        return None


def _add_swimlane_block(doc: Document, draft: ProcedureDraftOutput, figure_label: str):
    """
    Embed swimlane diagram(s) using the deterministic DiagramGenerator pipeline.

    Pipeline (v2 — no LLM):
        ProcedureDraftOutput
            → ProcedureParser  (DiagramSpec — deterministic)
            → LayoutEngine     (pixel positions — deterministic)
            → MatplotlibRenderer → PNG bytes

    Falls back to PlantUML text block only if rendering fails entirely.
    Auto-splits into multiple figures when procedure exceeds complexity limits.
    """
    fig_p = doc.add_paragraph()
    fig_p.add_run(figure_label).bold = True

    # ── Deterministic DiagramGenerator pipeline ────────────────────────────────
    try:
        from .agents.diagram_generator import DiagramGenerator
        png_list = DiagramGenerator().generate_swimlane(draft)
        if png_list:
            for i, png_bytes in enumerate(png_list):
                try:
                    doc.add_picture(io.BytesIO(png_bytes), width=Inches(6.5))
                    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
                    if len(png_list) > 1:
                        doc.add_paragraph(
                            f"  Figure 1.{i + 1}: Part {i + 1} of {len(png_list)}"
                        ).italic = True
                except Exception as exc:
                    print(f"[Renderer] Failed to insert swimlane part {i + 1}: {exc}")
            return
    except Exception as exc:
        print(f"[Renderer] DiagramGenerator failed ({exc}); using PlantUML fallback.")

    # ── Last resort: PlantUML text block ──────────────────────────────────────
    _add_plantuml_block(doc, draft.swimlane_diagram, "")


def render_procedure(
    draft: ProcedureDraftOutput,
    bundles: list[ControlBundle],
    output_dir: str = OUTPUT_DIR,
) -> tuple[str, str]:
    """
    Render a Golden Procedure Baseline document as two DOCX files:
      <doc_id>.docx               — formatted procedure document
      <doc_id>_traceability.docx  — control traceability annex
    Returns (main_path, annex_path).
    """
    os.makedirs(output_dir, exist_ok=True)
    safe_id    = draft.doc_id.replace("/", "-")
    main_path  = os.path.join(output_dir, f"{safe_id}.docx")
    annex_path = os.path.join(output_dir, f"{safe_id}_traceability.docx")

    chunk_map = {b.chunk_id: b for b in bundles}
    ctrl_map  = {b.control_id: b for b in bundles}

    # ── Main Procedure Document ───────────────────────────────────────────────
    doc = Document()

    # Cover block
    cover = doc.add_paragraph()
    cover.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = cover.add_run(draft.title_en.upper())
    r.bold = True
    r.font.size = Pt(20)
    r.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

    for line in [
        f"Document ID: {draft.doc_id}",
        f"Version: {draft.version}",
        f"Effective Date: {draft.effective_date}",
        f"Owner: {draft.owner}",
        f"Classification: {draft.classification}",
        f"Parent Policy: {draft.parent_policy_id}",
        f"Parent Standard: {draft.parent_standard_id}",
        f"Generated: {draft.generated_at[:10]}",
    ]:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.add_run(line).font.size = Pt(11)

    doc.add_page_break()

    # Table of Contents (15 sections)
    _hdr(doc, "Table of Contents")
    for i, heading in enumerate(PROCEDURE_TOC, start=1):
        doc.add_paragraph(f"{i}.  {heading}", style="List Number")
    doc.add_page_break()

    # ── §1. Definitions and Abbreviations ─────────────────────────────────────
    _hdr(doc, "1.  Definitions and Abbreviations")
    if draft.definitions:
        tbl_def = doc.add_table(rows=1, cols=2)
        tbl_def.style = "Table Grid"
        _tbl_hdr_row(tbl_def, ["Term / Abbreviation", "Definition"])
        for d in draft.definitions:
            row = tbl_def.add_row()
            row.cells[0].text = d.term
            row.cells[1].text = d.definition
            for cell in row.cells:
                _small(cell)
    else:
        doc.add_paragraph("See parent policy and standard for terminology definitions.")

    # ── §2. Procedure Objective ───────────────────────────────────────────────
    _hdr(doc, "2.  Procedure Objective")
    doc.add_paragraph(draft.objective_en)

    # ── §3. Scope and Applicability ───────────────────────────────────────────
    _hdr(doc, "3.  Scope and Applicability")
    doc.add_paragraph(draft.scope_en)

    # ── §4. Roles and Responsibilities ────────────────────────────────────────
    _hdr(doc, "4.  Roles and Responsibilities")
    tbl_roles = doc.add_table(rows=1, cols=2)
    tbl_roles.style = "Table Grid"
    _tbl_hdr_row(tbl_roles, ["Role", "Responsibilities"])
    for role in draft.roles_responsibilities:
        row = tbl_roles.add_row()
        row.cells[0].text = role.role_title
        row.cells[1].text = "\n".join(
            f"• {resp}" for resp in role.responsibilities
        )
        for cell in row.cells:
            _small(cell)

    # ── §5. Procedure Overview ────────────────────────────────────────────────
    _hdr(doc, "5.  Procedure Overview")
    if draft.procedure_overview:
        doc.add_paragraph(draft.procedure_overview)
    else:
        _n_phases = len(draft.phases)
        _n_total  = sum(len(ph.steps) for ph in draft.phases)
        doc.add_paragraph(
            f"This procedure comprises {_n_phases} phases and {_n_total} discrete steps. "
            f"Phases: {', '.join(ph.phase_name for ph in draft.phases)}."
        )

    # ── §6. Triggers, Prerequisites, Inputs and Tools ─────────────────────────
    _hdr(doc, "6.  Triggers, Prerequisites, Inputs and Tools")

    # 6.1 Triggers
    _hdr(doc, "6.1  Procedure Triggers", level=2)
    if draft.triggers:
        tbl_trg = doc.add_table(rows=1, cols=2)
        tbl_trg.style = "Table Grid"
        _tbl_hdr_row(tbl_trg, ["Trigger Event", "Description"])
        for trg in draft.triggers:
            row = tbl_trg.add_row()
            row.cells[0].text = trg.trigger
            row.cells[1].text = trg.description
            for cell in row.cells:
                _small(cell)
    else:
        doc.add_paragraph("Triggers are defined in the parent procedure specification.")

    # 6.2 Prerequisites
    _hdr(doc, "6.2  Prerequisites", level=2)
    for i, prereq in enumerate(draft.prerequisites, start=1):
        doc.add_paragraph(f"{i}. {prereq}", style="List Number")

    # 6.3 Input Forms and Templates
    if draft.input_forms:
        _hdr(doc, "6.3  Input Forms and Templates", level=2)
        tbl_forms = doc.add_table(rows=1, cols=3)
        tbl_forms.style = "Table Grid"
        _tbl_hdr_row(tbl_forms, ["Form Name", "Purpose", "Reference"])
        for f in draft.input_forms:
            row = tbl_forms.add_row()
            row.cells[0].text = f.form_name
            row.cells[1].text = f.purpose
            row.cells[2].text = f.reference
            for cell in row.cells:
                _small(cell)

    # 6.4 Tools Required
    _hdr(doc, "6.4  Tools Required", level=2)
    tbl_tools = doc.add_table(rows=1, cols=2)
    tbl_tools.style = "Table Grid"
    _tbl_hdr_row(tbl_tools, ["#", "Tool / Resource"])
    for i, tool in enumerate(draft.tools_required, start=1):
        row = tbl_tools.add_row()
        row.cells[0].text = str(i)
        row.cells[1].text = tool
        for cell in row.cells:
            _small(cell)

    # ── §7. Detailed Procedure Steps ──────────────────────────────────────────
    _hdr(doc, "7.  Detailed Procedure Steps")

    # Swimlane diagram (proper grid: roles × phases)
    doc.add_paragraph()
    _add_swimlane_block(doc, draft, "Figure 1: Process Swimlane Diagram")
    _roles_str  = ", ".join(r.role_title for r in draft.roles_responsibilities)
    _phases_str = ", ".join(ph.phase_name for ph in draft.phases)
    _n_steps    = sum(len(ph.steps) for ph in draft.phases)
    _add_diagram_explanation(doc,
        f"Figure 1 illustrates the procedure workflow across {len(draft.phases)} phases "
        f"({_phases_str}). Each horizontal lane represents a distinct actor: {_roles_str}. "
        f"Arrows show the handover sequence between roles. Diamond shapes indicate "
        f"decision/validation checkpoints where a pass or fail outcome determines the next "
        f"action. The procedure comprises {_n_steps} discrete steps in total."
    )
    doc.add_paragraph()

    # ── Figure 2: Process Flowchart (native matplotlib — no external server) ──
    try:
        from .agents.diagram_generator import DiagramGenerator
        fc_png_list = DiagramGenerator().generate_flowchart_png(draft)
        if fc_png_list:
            _hdr(doc, "Figure 2: Process Flowchart", level=2)
            for fc_png in fc_png_list:
                doc.add_picture(io.BytesIO(fc_png), width=Inches(6.0))
                doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
            _add_diagram_explanation(doc,
                  "Figure 2 presents the end-to-end process logic from initiation to completion. "
                  "Each phase is separated by a banner; decision diamonds indicate branching logic.")
        else:
            raise RuntimeError("generate_flowchart_png returned empty list")
    except Exception as exc:
        print(f"[Renderer] Flowchart PNG generation failed ({exc}) — skipping Figure 2.")
    doc.add_paragraph()

    # Phases and steps
    for phase in draft.phases:
        _hdr(doc, f"Phase: {phase.phase_name}", level=2)
        if phase.phase_intro:
            doc.add_paragraph(phase.phase_intro)
        for local_no, step in enumerate(phase.steps, start=1):
            step_p = doc.add_paragraph(style="List Bullet")
            step_id_run = step_p.add_run(f"Step {local_no}  [{step.actor}]  ")
            step_id_run.bold = True
            step_id_run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)
            step_p.add_run(step.action)

            out_p = doc.add_paragraph(style="List Bullet 2")
            out_p.add_run("Expected Output: ").bold = True
            out_p.add_run(step.expected_output).font.size = Pt(9)

            if step.code_block.strip():
                _add_code_block(doc, step.code_block)

            if step.citations:
                resolved = []
                for cid in step.citations:
                    b = chunk_map.get(cid)
                    if b:
                        resolved.append(b.control_id)
                if resolved:
                    cite_p = doc.add_paragraph()
                    cite_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
                    r_cite = cite_p.add_run("  ·  ".join(resolved))
                    r_cite.font.size = Pt(7.5)
                    r_cite.font.color.rgb = RGBColor(0x70, 0x70, 0x70)
                    r_cite.italic = True

    # 7a. Verification and Quality Checks (sub-section)
    _hdr(doc, "7a.  Verification and Quality Checks", level=2)
    tbl_ver = doc.add_table(rows=1, cols=5)
    tbl_ver.style = "Table Grid"
    _tbl_hdr_row(tbl_ver, ["Check ID", "Description", "Method", "Expected Result", "Evidence Artifact"])
    for chk in draft.verification_checks:
        row = tbl_ver.add_row()
        row.cells[0].text = chk.check_id
        row.cells[1].text = chk.description
        row.cells[2].text = chk.method
        row.cells[3].text = chk.expected_result
        row.cells[4].text = chk.evidence_artifact
        for cell in row.cells:
            _small(cell)

    # ── §8. Decision Points, Exceptions and Escalations ──────────────────────
    _hdr(doc, "8.  Decision Points, Exceptions and Escalations")
    if draft.decision_points_and_escalations:
        doc.add_paragraph(draft.decision_points_and_escalations)
    if draft.exception_handling_en:
        _hdr(doc, "8.1  Exception Handling", level=2)
        doc.add_paragraph(draft.exception_handling_en)

    # ── §9. Outputs, Records, Evidence and Forms ──────────────────────────────
    _hdr(doc, "9.  Outputs, Records, Evidence and Forms")

    if draft.outputs_records:
        _hdr(doc, "9.1  Procedure Outputs", level=2)
        tbl_out = doc.add_table(rows=1, cols=2)
        tbl_out.style = "Table Grid"
        _tbl_hdr_row(tbl_out, ["Output / Deliverable", "Recipient / Destination"])
        for o in draft.outputs_records:
            row = tbl_out.add_row()
            row.cells[0].text = o.output
            row.cells[1].text = o.recipient_or_destination
            for cell in row.cells:
                _small(cell)

    if draft.evidence_records:
        _hdr(doc, "9.2  Evidence and Audit Records", level=2)
        tbl_evr = doc.add_table(rows=1, cols=4)
        tbl_evr.style = "Table Grid"
        _tbl_hdr_row(tbl_evr, ["Record / Evidence", "Owner", "Retention", "Storage Location"])
        for er in draft.evidence_records:
            row = tbl_evr.add_row()
            row.cells[0].text = er.record_or_evidence
            row.cells[1].text = er.owner
            row.cells[2].text = er.retention
            row.cells[3].text = er.storage_location
            for cell in row.cells:
                _small(cell)

    if draft.evidence_collection:
        _hdr(doc, "9.3  Evidence Collection Checklist", level=2)
        doc.add_paragraph(
            "The following artifacts shall be collected and retained as evidence of "
            "procedure execution and control compliance:"
        )
        tbl_ev = doc.add_table(rows=1, cols=2)
        tbl_ev.style = "Table Grid"
        _tbl_hdr_row(tbl_ev, ["#", "Evidence Artifact"])
        for i, ev in enumerate(draft.evidence_collection, start=1):
            row = tbl_ev.add_row()
            row.cells[0].text = str(i)
            row.cells[1].text = ev
            for cell in row.cells:
                _small(cell)

    # ── §10. Time Controls, Service Levels and Control Checkpoints ────────────
    _hdr(doc, "10.  Time Controls, Service Levels and Control Checkpoints")
    if draft.time_controls:
        tbl_tc = doc.add_table(rows=1, cols=4)
        tbl_tc.style = "Table Grid"
        _tbl_hdr_row(tbl_tc, ["Activity / Step", "Service Level (SLA)", "Responsible Role", "Escalation if Breached"])
        for tc in draft.time_controls:
            row = tbl_tc.add_row()
            row.cells[0].text = tc.activity_or_step
            row.cells[1].text = tc.service_level
            row.cells[2].text = tc.responsible_role
            row.cells[3].text = tc.escalation_if_breached
            for cell in row.cells:
                _small(cell)
    else:
        doc.add_paragraph("Service level agreements are defined in the parent standard.")

    # ── §11. Related Documents ────────────────────────────────────────────────
    _hdr(doc, "11.  Related Documents")
    related = list(draft.related_documents)
    if draft.parent_policy_id and f"Parent Policy: {draft.parent_policy_id}" not in related:
        related.insert(0, f"Parent Policy: {draft.parent_policy_id}")
    if draft.parent_standard_id and f"Parent Standard: {draft.parent_standard_id}" not in related:
        related.insert(1, f"Parent Standard: {draft.parent_standard_id}")
    for doc_ref in related:
        doc.add_paragraph(doc_ref, style="List Bullet")

    # ── §12. Effective Date ───────────────────────────────────────────────────
    _hdr(doc, "12.  Effective Date")
    doc.add_paragraph(
        f"This procedure is effective from {draft.effective_date}. "
        f"All previous versions of this procedure are superseded upon this date."
    )

    # ── §13. Procedure Review ─────────────────────────────────────────────────
    _hdr(doc, "13.  Procedure Review")
    if draft.procedure_review:
        doc.add_paragraph(draft.procedure_review)
    else:
        doc.add_paragraph(
            "This procedure shall be reviewed annually or upon: (a) major changes to "
            "systems, processes, or tools referenced herein; (b) changes to the parent "
            "policy or standard; (c) changes in regulatory or legislative requirements; "
            "or (d) after any significant incident involving the process covered by this procedure."
        )

    # ── §14. Review and Approval ──────────────────────────────────────────────
    _hdr(doc, "14.  Review and Approval")
    if draft.review_and_approval:
        doc.add_paragraph(draft.review_and_approval)
    tbl_appr = doc.add_table(rows=1, cols=4)
    tbl_appr.style = "Table Grid"
    _tbl_hdr_row(tbl_appr, ["Role", "Name", "Signature", "Date"])
    for appr_role in ["Prepared by", "Reviewed by", "Recommended by", "Approved by"]:
        row = tbl_appr.add_row()
        row.cells[0].text = appr_role
        row.cells[1].text = ""
        row.cells[2].text = ""
        row.cells[3].text = ""
        for cell in row.cells:
            _small(cell)

    # ── §15. Version Control ──────────────────────────────────────────────────
    _hdr(doc, "15.  Version Control")
    tbl_vc = doc.add_table(rows=1, cols=4)
    tbl_vc.style = "Table Grid"
    _tbl_hdr_row(tbl_vc, ["Version", "Date", "Author", "Description of Changes"])
    row = tbl_vc.add_row()
    row.cells[0].text = draft.version
    row.cells[1].text = draft.effective_date
    row.cells[2].text = draft.owner
    row.cells[3].text = "Initial release"
    for cell in row.cells:
        _small(cell)

    doc.add_page_break()
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_p.add_run(
        f"Generated by AutoAlign Policy Factory (15-Section Procedure) | "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    ).font.size = Pt(8)

    print(f"[Renderer] Writing procedure -> {main_path}")
    doc.save(main_path)

    # ── Traceability Annex ────────────────────────────────────────────────────
    ann = Document()
    _hdr(ann, "Control Traceability Annex")
    ann.add_paragraph(
        f"Document: {draft.doc_id}  |  {draft.title_en}  |  Version: {draft.version}"
    ).runs[0].font.size = Pt(10)
    ann.add_paragraph(
        f"Parent Policy: {draft.parent_policy_id}  |  Parent Standard: {draft.parent_standard_id}"
    ).runs[0].font.size = Pt(9)
    ann.add_paragraph(
        "This annex maps every procedure step to the cybersecurity controls that ground it. "
        "Steps with citations are directly traceable to the NCA control library. "
        "The Rerank Score column shows cross-encoder relevance."
    ).runs[0].font.size = Pt(9)

    # Step-level traceability table
    hdrs = ["Step", "Phase", "Actor", "Action (excerpt)",
            "Control IDs", "Framework", "NCA ID", "Rerank Score"]
    tbl2 = ann.add_table(rows=1, cols=len(hdrs))
    tbl2.style = "Table Grid"
    _tbl_hdr_row(tbl2, hdrs)

    for phase in draft.phases:
        # Phase separator
        sep = tbl2.add_row()
        sep_cell = sep.cells[0]
        sep_cell.merge(sep.cells[-1])
        sep_cell.text = f"Phase: {phase.phase_name}"
        _set_cell_bg(sep_cell, _LIGHT)
        for para in sep_cell.paragraphs:
            for run in para.runs:
                run.bold = True
                run.font.size = Pt(9)

        for step in phase.steps:
            if step.citations:
                for cid in step.citations:
                    b = chunk_map.get(cid)
                    row = tbl2.add_row()
                    cells = row.cells
                    cells[0].text = step.step_no
                    cells[1].text = step.phase
                    cells[2].text = step.actor
                    cells[3].text = step.action[:150] + ("..." if len(step.action) > 150 else "")
                    cells[4].text = b.control_id if b else cid
                    cells[5].text = b.framework if b else "-"
                    cells[6].text = (b.nca_id or b.uae_ia_id or "-") if b else "-"
                    score = b.rerank_score if b else None
                    cells[7].text = f"{score:.4f}" if score is not None else "-"
                    if score is not None and score > 5.0:
                        _set_cell_bg(cells[7], _GREEN)
                    for cell in cells:
                        _small(cell)
            else:
                # Uncited step — single row with no control info
                row = tbl2.add_row()
                cells = row.cells
                cells[0].text = step.step_no
                cells[1].text = step.phase
                cells[2].text = step.actor
                cells[3].text = step.action[:150] + ("..." if len(step.action) > 150 else "")
                cells[4].text = "-"
                cells[5].text = "-"
                cells[6].text = "-"
                cells[7].text = "-"
                for cell in cells:
                    _small(cell)

    # Cross-document traceability summary
    _hdr(ann, "Cross-Document Control Coverage", level=2)
    ann.add_paragraph(
        "The table below shows which NCA controls are covered by this procedure, "
        "linking procedure steps to the governance hierarchy."
    ).runs[0].font.size = Pt(9)

    hdrs2 = ["Control ID", "Source Framework", "Control Title",
             "NCA ID", "Procedure Steps"]
    tbl3 = ann.add_table(rows=1, cols=len(hdrs2))
    tbl3.style = "Table Grid"
    _tbl_hdr_row(tbl3, hdrs2)

    # Build: control_id -> list of step_no that cite it
    ctrl_to_steps: dict[str, list[str]] = {}
    for phase in draft.phases:
        for step in phase.steps:
            for cid in step.citations:
                b = chunk_map.get(cid)
                ctrl_id = b.control_id if b else cid
                ctrl_to_steps.setdefault(ctrl_id, []).append(step.step_no)

    for ctrl_id, step_nos in sorted(ctrl_to_steps.items()):
        b = ctrl_map.get(ctrl_id)
        row = tbl3.add_row()
        row.cells[0].text = ctrl_id
        row.cells[1].text = b.framework if b else "-"
        row.cells[2].text = b.title if b else "-"
        row.cells[3].text = (b.nca_id or b.uae_ia_id or "-") if b else "-"
        row.cells[4].text = ", ".join(step_nos)
        for cell in row.cells:
            _small(cell)

    print(f"[Renderer] Writing procedure traceability annex -> {annex_path}")
    ann.save(annex_path)

    total_steps = sum(len(ph.steps) for ph in draft.phases)
    cited_steps = sum(
        1 for ph in draft.phases for st in ph.steps if st.citations
    )
    print(f"[Renderer] Procedure render done: {len(draft.phases)} phases, "
          f"{total_steps} steps ({cited_steps} cited).")
    return main_path, annex_path
