"""
Diagram Agent — deterministic diagram generation for procedure documents (v2).

Architecture change (v2):
  OLD: LLM (gpt-5.4) generates Mermaid swimlane + flowchart code → non-deterministic,
       prone to syntax errors, requires QA validation loop.

  NEW: Deterministic pipeline — no LLM, no syntax errors, no validation needed.
       Both swimlane and flowchart are generated algorithmically from procedure data.

This agent is the fallback called by the pipeline when QA detects missing or
invalid diagrams. With v2 the output is always valid (no LLM hallucinations).
"""
from __future__ import annotations

from ..models import ProcedureDraftOutput, ProcedurePhase, ProcedureRoleItem
from .diagram_generator import DiagramGenerator


class DiagramAgent:
    """
    Deterministic fallback diagram generator for PRC-* procedure documents.

    Called when the primary drafter produces diagrams that fail QA validation.
    Unlike v1, this agent makes no LLM API calls — output is always valid.
    """

    def __init__(self) -> None:
        self._generator = DiagramGenerator()

    def generate(
        self,
        title: str,
        phases: list[ProcedurePhase],
        roles: list[ProcedureRoleItem],
        topic: str,
    ) -> tuple[str, str]:
        """
        Generate swimlane and flowchart diagram representations.

        Returns:
            swimlane_code  — empty string (swimlane is rendered as PNG directly)
            flowchart_code — PlantUML activity diagram code

        The swimlane PNG is generated by DiagramGenerator.generate_swimlane()
        at render time in renderer.py. There is no text-based swimlane code.
        """
        print(f"[DiagramAgent] Generating deterministic diagrams for: {title}")

        # Build a minimal ProcedureDraftOutput for the generator
        from ..models import ProcedureDefinition
        from datetime import datetime, timezone

        draft = ProcedureDraftOutput(
            doc_id=f"DRAFT_{title[:20].replace(' ', '_')}",
            title_en=title,
            version="1.0",
            effective_date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            owner="Cybersecurity Department",
            classification="Internal",
            parent_policy_id="POL-00",
            parent_standard_id="STD-00",
            objective_en=f"Procedure for {topic}",
            scope_en="All systems and staff within scope.",
            roles_responsibilities=roles,
            prerequisites=[],
            tools_required=[],
            phases=phases,
            verification_checks=[],
            evidence_collection=[],
            exception_handling_en="Escalate exceptions to the Cybersecurity Department.",
            swimlane_diagram="",
            flowchart_diagram="",
        )

        flowchart_code = self._generator.generate_flowchart_code(draft)
        swimlane_code  = ""   # PNG rendered directly at DOCX generation time

        print(
            f"[DiagramAgent] Done: flowchart {len(flowchart_code)} chars PlantUML."
        )
        return swimlane_code, flowchart_code
